config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root 'recipes#top'

  get 'users/:id/edit' => 'users#edit', as: 'edit_user'

resources :users

resources :recipes do
	get "search", on: :collection
resources :recipe_items
resources :favorites,only:[:create,:destroy]
end

get "myfavorites" => "favorites#index", as: "myfavorites"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

 def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  validates :title, presence: true
  validates :recipe_image, presence: true


attachment :recipe_image

  has_many :favorites
  has_many :recipe_items,dependent: :destroy
  belongs_to :user

accepts_nested_attributes_for :recipe_items, allow_destroy: true

  default_scope -> {order(id: :desc)}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
  	if search
  		where(['title LIKE ?', "%#{search}%"])
  	else
  		Recipe.all
  	end
  end

end

app/models/recipe_item.rb
class RecipeItem < ApplicationRecord

	belongs_to :recipe

	attachment :stroke_image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :image

  has_many :favorites, dependent: :destroy
  has_many :recipes, dependent: :destroy, through: :favorites

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    recipes_path(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    recipes_path(resource)
    root_path
  end

protected

  def configure_permitted_parameters
    # sign_upのときに、nameをストロングパラメータに追加する
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])

    devise_parameter_sanitizer.permit(:log_in, keys: [:name, :email])

    # account_updateのときに、nameをストロングパラメータに追加する
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
  @user = current_user
  @recipes = current_user.recipes
   @recipes = Kaminari.paginate_array(@recipes).page(params[:page]).per(9)

end
  def create
  	recipe = Recipe.find(params[:recipe_id])
  	favorite = current_user.favorites.new(recipe_id: recipe.id)
  	favorite.save
    redirect_to recipe_path(recipe)
  end

  def destroy
  	recipe = Recipe.find(params[:recipe_id])
  	favorite = current_user.favorites.find_by(recipe_id: recipe.id)
  	favorite.destroy
    redirect_to recipe_path(recipe)
  end

end

app/controllers/fovorites_controller.rb
class FovoritesController < ApplicationController

  def create
  	recipe = Recipe.find(params[:recipe_id])
  	favorite = current_user.favorite.new(recipe_id: recipe_id)
  	favorite.save
    redirect_to recipe_path
  end

  def destroy
  	recipe = Recipe.find(params[:recipe_id])
  	favorite = current_user.favorite.find_by(recipe_id: recipe_id)
  	favorite.destroy
    redirect_to recipe_path
  end

end

app/controllers/recipe_items_controller.rb
class RecipeItemsController < ApplicationController

  def new
  	@recipe_item = Recipe_item.new
  end

private

  def recipe_item
  	prams.reqire(:recipe_item).permit(:seasoning, :stloke_image)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
   def index
   recipe_favorite_count = Recipe.joins(:favorites).group(:recipe_id).count
   recipe_favorite_ids = Hash[recipe_favorite_count.sort_by{ |_, v| -v}].keys
   @recipe_ranking = Recipe.where(id: recipe_favorite_ids)
   @recipes = Recipe.page(params[:page]).per(9)
   end

  # def search
  # @recipes = Recipe.search(params[:search])
  # @recipes = Recipe.page(params[:page]).per(9)
  # render "top"
  # end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
  	@recipe = Recipe.new
  	@recipe.recipe_items.build
  end

  def top
    if params[:search]
      @recipes = Recipe.search(params[:search])
      @recipes = Kaminari.paginate_array(@recipes).page(params[:page]).per(9)
    else
      @recipes = Recipe.page(params[:page]).per(9)
    end
  end


  def create
  	@recipe = Recipe.new(recipe_params)
  	#binding.pry
  	@recipe.user_id = current_user.id
  	@recipe.save
  	redirect_to root_path
  end

  def edit
  	@recipe = Recipe.find(params[:id])
  end

  def update
  	recipe = Recipe.find(params[:id])
    recipe.update(recipe_params)
    redirect_to root_path
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to root_path
  end

private

  def recipe_params
 	params.require(:recipe).permit(:title, :recipe_image, recipe_items_attributes:[:id, :seasoning, :stroke_image, :_destroy])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@user =User.all
  end

  def show
    @user = User.find(params[:id])
    @recipes = Recipe.where(user_id: @user.id)
    @recipes = Kaminari.paginate_array(@recipes).page(params[:page]).per(9)
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)
  end

  def delete
  end

  def destroy
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to root_path, notice: "削除しました。"
  end

  private
  def user_params
  	params.require(:user).permit(:name, :email, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/recipe_items_helper.rb
module RecipeItemsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<%= render 'users/header' ,user:@user %>
  <div class="container">
    <div class="row">
         <ul class="nav nav-tabs nav-justified">
           <li role="presentation"><a href="/">新着</a></li>
           <li role="presentation"><a href="/recipes">ランキング</a></li>
          </ul>
<div class="flex">
  

      <% @recipes.each do |recipe| %>
              <div class="flex-container"><div><%= link_to recipe_path(recipe) do %>
                <%= attachment_image_tag recipe, :recipe_image, :fill,300,300,format: 'jpg', size: "300x300",fallback:"no_image.png" %>
              <% end %></div>
                    <h4><%= recipe.title %></h4>
              </div>
        <% end %>
        </div>
          <div style="text-align: center;"><%= paginate @recipes %></div>
      </div>
   </div>
 </div>

<%= render 'users/footer' ,user:@user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb


<div class="row">
  
<div class="col-sm-4">
      <%= attachment_image_tag @recipe, :recipe_image, :fill,420,380,format: 'jpg', size: "420x380",fallback:"no_image.png" %>
    </div>
      <div class="col-sm-2"></div>
 <div class="col-sm-6">
<%= form_for recipe do |f| %>
  <div class="container_left">
    
    <div class="recipe_image_select">
      <%= f.attachment_field :recipe_image %>
      <%= f.text_field :title, placeholder: "レシピ名" %>
      <%= f.submit '投稿' %>
    </div>
      <%#= f.label :レシピ名　%>
     <%#= f.submit '保存' %>
  </div>
<%= f.label :行程 %>
  <%= f.fields_for :recipe_items do |recipe_item| %>
   
    <%= render 'recipe_item_fields', f: recipe_item %>
  <% end %>
    <div class="rhite_field">
      <!-- <div class="links"> -->
      <%= link_to_add_association "行を追加する", f, :recipe_items, class: "btn btn-success  btn" %>
      <!-- </div> -->
    </div>
         <%#= render 'stroke_fields', f: recipe_item %>
         <%# end %>
<% end %>

   </div>
</div>

app/views/recipes/_form2.html.erb
<%#= form_for recipe do |f| %>
 <!-- <div class="add_form"> -->
  <!-- <div class="field"> -->
    <!-- <%#= f.label :title %> -->
    <!-- <%#= f.text_field :title, required: true %> -->
  <!-- </div> -->

     <!-- <label></label> -->
     <!-- <div class="add_stroke"> -->
       <%#= f.fields_for :recipe_items do |recipe_item| %>
         <%#= render 'stroke_fields', f: recipe_item %>
       <%# end %>
      <!-- <div class="links"> -->
        <%#= link_to_add_association "行を追加する", f, :recipe_items, class: "btn btn-success  btn" %>
      <!-- </div> -->
    <!-- </div> -->
         <%#= render 'stroke_fields', f: recipe_item %>
         <%# end %>
    <%#= f.submit '投稿'%>
<%# end %>
 <!-- <div class="add_form"> -->


app/views/recipes/_recipe_item_fields.html.erb
<div class="rhite_field">
  <div class="nested-fields">
      <%= f.file_field :stroke_image, class: 'file_field' %>
      <%= f.text_field :seasoning, required: true %>
      <%= link_to_remove_association "✖", f, class: "btn btn-danger delete_btn" %>
  </div>
</div>


app/views/recipes/_stroke_fields.html.erb
<!-- <div class="nested-fields"> -->
  <!-- <div class="field"> -->
    <%#= f.label :材料 %>
    <!-- </br> -->
    <%#= f.text_field :seasoning, required: true %>
  <!-- </div> -->
  <%#= link_to_remove_association "✖", f, class: "btn btn-banger" %>
<!-- </div> -->



app/views/recipes/edit.html.erb
<%= render 'users/header' ,user:@user %>
<div class="container">
  <div class="row">
  	<div class="col-xs-12">
      <h3>レシピ編集</h3>
        <%= form_for (@recipe) do |f| %>
          <%= render 'recipes/form' ,recipe:@recipe %>
     </div>
        <div class="row">
          <div class=col-xs-12>
            <%= f.text_field :title %>
            <%= f.submit '保存' %>
          </div>
        </div>

<% end %>

app/views/recipes/index.html.erb
<%= render 'users/header' ,user:@user %>
  <div class="container">
    <div class="row">
         <ul class="nav nav-tabs nav-justified">
           <li role="presentation"><a href="/">新着</a></li>
           <li role="presentation"><a href="/recipes">ランキング</a></li>
          </ul>
<div class="flex">

      <% @recipe_ranking.each do |recipe_ranking| %>
              <div class="flex-container"><div>
              	<%#= recipe_favorites_count %>
              	<%= link_to recipe_path (recipe_ranking) do %>
                <%= attachment_image_tag recipe_ranking, :recipe_image, :fill,250,250,format: 'jpg', size: "250x250",fallback:"no_image.png" %>
              <% end %></div>
                    <h4><%= recipe_ranking.title %></h4>
              </div>
        <% end %>
        </div>
         <div style="text-align: center;"><%= paginate @recipes %></div>
      </div>
   </div>
 </div>

<%= render 'users/footer' ,user:@user %>

app/views/recipes/new.html.erb
<%= render 'users/header' ,user:@user %>

<div class="container">

      <h3> レシピ投稿</h3>
            <%= render 'recipes/form' , recipe:@recipe %>
          	<%#= render 'recipes/form2' ,recipe:@recipe %>



app/views/recipes/show.html.erb
<%= render 'users/header' ,user:@user %>

<div class="container">
  <!-- <div class="row"> -->
    <div class="col-12">
      <h3>レシピ詳細ページ</h3>
        <div class="dispray_image">
          <%= attachment_image_tag @recipe, :recipe_image, :fill,450,380,format: 'jpg', size: "420x380",fallback:"no_image.png" %>
          <%= @recipe.title %>
          <% if @recipe.user == current_user %>
          <%= link_to "編集", edit_recipe_path(@recipe), class:"btn btn-success edit_btn" %>
          <%= link_to "削除", recipe_path(@recipe), method: :delete , class: "btn btn-denger delete_btn" %>
          <% end %>
        </div>
            <% if @recipe.favorited_by?(current_user) %>
              <li>
                <%= link_to  recipe_favorite_path(@recipe), method: :delete do %>
                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
               <%= @recipe.favorites.count %> お気に入り

            <% end %>
              </li>
            <% else %>
             <li>
               <%= link_to  recipe_favorites_path(@recipe), method: :post do %>
               <i class="fa fa-heart-o" aria-hidden="true"></i>
               <%= @recipe.favorites.count %> お気に入り
              </li>
            <% end %>
          <% end %>
        </div>

        <% @recipe.recipe_items.each do |recipe_item| %>
           <div class="stroke_field">
           	<div><%=recipe_item.seasoning %></div>
           				<%= attachment_image_tag recipe_item, :stroke_image, :fill,150,150,format: 'jpg', size: "150x150",fallback:"no_image.png" %>
           </div>
         <% end %>

    </div>
  <!-- </div> -->
</div>

app/views/recipes/top.html.erb
<%= render 'users/header' ,user:@user %>
  <div class="container">
    <div class="row">
         <ul class="nav nav-tabs nav-justified">
           <li role="presentation"><a href="/">新着</a></li>
           <li role="presentation"><a href="/recipes">ランキング</a></li>
          </ul>

      <% @recipes.each do |recipe| %>
              <div class="flex-container"><div><%= link_to recipe_path(recipe) do %>
                <%= attachment_image_tag recipe, :recipe_image, :fill,250,250,format: 'jpg', size: "250x250",fallback:"no_image.png" %>
              <% end %></div>
                    <h4><%= recipe.title %></h4>
              </div>
        <% end %>
          <div style="text-align: center;"><%= paginate @recipes %></div>
      </div>
   </div>
 </div>





<%= render 'users/footer' ,user:@user %>

app/views/users/_footer.html.erb
<footer>
</footer>

app/views/users/_header.html.erb
<header>
  <div class="header">
	<%= link_to"今日の献立！" ,root_path %>
  </div>

  <div class="search">
    <%= form_tag root_path, :method =>'get' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "検索" %>
    <% end %>
  </div>

  <div class="not-sign-in-header">
    <%if current_user %>
      <%=current_user.name %>
         <%= link_to "マイページ" ,user_path(current_user.id) %>
          | <%=link_to "ログアウト", destroy_user_session_path, method: :delete %>

          | <%= link_to "レシピ投稿" ,new_recipe_path %>
          | <%= link_to "お気に入り一覧" ,myfavorites_path %>
    <%else%>

      <%= link_to "会員登録" ,new_user_registration_path %>
        &nbsp &nbsp
      <%= link_to "ログイン" ,new_user_session_path %>

  <% end %>

  </div>
</header>

app/views/users/edit.html.erb
<%= render 'users/header' ,user:@user %>
  <div id="st-container" class="st-container">
    <div class="st-pusher">
      <div class="st-content">
        <div class="st-content-inner">      
          <section class="slice slice-lg sct-color-1">
            <div class="container">
              <div class="row">
                <div class="col-md-4 col-md-offset-4">
                  <div class="form-user style-1 rounded has-shadow-1">
                    <div class="form-header text-center">
                      <h2 class="form-header-title">プロフィール編集</h2>
                    </div>
                  <div class="form-body">
                    <%= form_for(@user) do |f| %>
                    <div class="form-group has-icon">
                      <label class="control-label sr-only" for="inputEmail">Name</label>
                        <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
                          <%= f.email_field :email, autofocus: true, autocomplete: "email",placeholder: "メールアドレス", class: "form-control" %>
                          <div class="form-group has-icon">
                          <div class="user-edit-image">
                            <%= attachment_image_tag @user, :image, :fill, 60, 60, size: "200x200", class: "jpeg", fallback: "no_image.png"%>
                          </div>
                          <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
                          <%= f.attachment_field :image, placeholder: "プロフィール画像" %>
                        </div>
                        </div>
                        <%= f.submit "保存" %>
                    <% end %>
                    </div>
                  </div> 
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%#= render 'users/header' ,user:@user %>
<!-- <div class="col-sm-4">
  <div class="user-index-title"><h1>ユーザー 一覧</h1></div>
</div>

<div class="col-sm-4"></div>
  <table class="table table-bordered">
    <thead>
	  <tr>
	    <th class="image_index_display">ユーザー画像</th>
		<th class="name_index_display">名前</th>
		<th class="email_index_diesplay">メール</th>
		<th class="edit_index_display">編集</th>
		<th class="delete_index_display">削除</th>
	  </tr>
	</thead> -->
	<%# @user.each do |user| %>
	<!--   <tbody class="taikai">
		<tr>
			<td class="image_index_display"><%#= attachment_image_tag user, :image, :fill,50,50, format: 'jpeg', size: "50x50", fallback: "/images/no-image.png" %>
		    </td>
			<td class="name_index_display"><%#= user.name %></td>

			<td class="email_index_diespla"><%= user.email %></td>

			<td class="edit_index_display"><%#= link_to "編集",edit_user_path(user.id), class: "btn btn-success  btn-xs" %></td>
			<td class="delete_index_display"><%=# link_to "削除", root_path, method: :delete, date: { confirm: "本当に削除しますか？"}, class: "btn btn-danger" %></td>
		</tr>
	</tbody>
	<% #end %>
</table> -->

app/views/users/show.html.erb
<%= render 'users/header' ,user:@user %>

<div class="container">
  <div> <h1>マイページ</h1></div>
    <div class="row">
      <div class="col-xs-12">
        <div align="center">
          <div>
            <%= attachment_image_tag @user, :image, :fill,100,100, format: 'jpeg', size: "200x200", fallback: "no_image.png" %>
          </div>
        <div>
      <div> <%= @user.name %> </div>
      <div> <%=@user.email %> </div>
	     <%= link_to "編集",edit_user_path(@user.id), class: "btn btn-success edit_btn" %>
		     <%= link_to "退会", user_registration_path,method: :delete, class: "btn btn-danger delete_btn" %>
         </div>
       </div>
     </div>
   </div>
</div>
<div align="center"><h4>投稿一覧  ↓</h4></div>
<div class="flex">
  

      <% @recipes.each do |recipe| %>
              <div class="flex-container"><div><%= link_to recipe_path(recipe) do %>
                <%= attachment_image_tag recipe, :recipe_image, :fill,300,300,format: 'jpg', size: "300x300",fallback:"no_image.png" %>
              <% end %></div>
                    <h4><%= recipe.title %></h4>
              </div>
        <% end %>
        </div>
          <div style="text-align: center;"><%= paginate @recipes %></div>
      </div>
   </div>
 </div>